project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "protocols/*.qmd"
    - "experiments/*.qmd"
    - "experiments/_templates/*.qmd"

website:
  title: "JP Flores' Lab Notebook"
  description: "Protocols and experiment entries"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Protocols"
        href: protocols/index.qmd
      - text: "Experiments"
        href: experiments/index.qmd
    right:
      - icon: github
        href: https://github.com/jpflores-13/lab_notebook
        aria-label: GitHub

  sidebar:
    - title: "Protocols"
      style: "docked"
      contents:
        - protocols/index.qmd
        - auto: "protocols/*.qmd"

    - title: "Experiments"
      style: "docked"
      contents:
        - experiments/index.qmd
        - auto: "experiments/*.qmd"

  page-footer:
    center: "JP Flores"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    toc-float: true
    number-sections: false
    code-fold: true
    code-tools: true
    highlight-style: github
    css: styles.css

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
